### ISSUE TITLE
Clarification on GPT-4 Versions for FollowBench

### ISSUE THREAD

**Issue by X1AOX1A** [THU-KEG/Crab#1]
Hi Grad Authors,

Could you please clarify the specific versions of GPT-4 used during the evaluation process of FollowBench (e.g., gpt-4-xxxx)?

For reference, here is the official list of GPT-4 version names provided by OpenAI: [GPT-4 Model Documentation](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4).

Thank you for your help!

**Comment by kijlk** [comment]
We used gpt-4o-2024-08-06.
