### ISSUE TITLE
Request for Intermediate Files from Data Synthesis Process

### ISSUE THREAD

**Issue by X1AOX1A** [THU-KEG/Crab#2]
Hello Grab Author, 

Would you kindly share the intermediate files from the data synthesis process? Having access to these would be extremely helpful and save considerable time and effort in recreating them.

Thank you very much for your consideration and any assistance you can provide.

**Comment by kijlk** [comment]
Thank you for your suggestion. Due to the large size of the intermediate data file, I will release it at a later time.
