### ISSUE TITLE
OpenAI API for Generation

### ISSUE THREAD

**Issue by Liuziyu77** [THU-KEG/Crab#3]
It seems that there might be an issue with the query_openai_chat_model function in .eval.utils. Could you please explain how to use this function to call OpenAI’s API to generate responses? Also, should any additional parameters be added to the Crab_1_Constraint_Back_Translation.sh file? And where exactly should the OpenAI API key be entered?

**Comment by kijlk** [comment]
Thank you for your question.  Actually, the entire data generation process in Crab does not use OpenAI’s API, but instead uses LLaMA 3 to complete the data generation. Therefore, we do not involve the input of the OpenAI API key. For the .eval section, we based our implementation on the open-instruct repository (https://github.com/allenai/open-instruct), and you can refer to the calling method in Crab_1_Constraint_Back_Translation.sh. 
For example:
```
CUDA_VISIBLE_DEVICES=${CUDA} python eval/predict.py \
    --model_name_or_path ${Lama3_Path} \
    --input_files ${input} \
    --output_file ${output} \
    --batch_size 4 \
    --use_vllm \
    --top_p 0.3 \
    --temperature 0.4 \
    --do_sample \
    --use_chat_format \
    --chat_formatting_function eval.templates.create_prompt_with_llama3_chat_format
```


Additionally, any other parameters not mentioned in the Crab_1_Constraint_Back_Translation.sh file are set to the default values in the code. Please refer to the code for details.
